### ISSUE TITLE
Add table of contents to readme

### ISSUE THREAD

**Issue by okaune** [ludens-reklamebyra/react-crisscross#54]
**Is your feature request related to a problem? Please describe.**
The readme is now of a length where it would be beneficial to have a TOC in order to find what you are looking for more easily

**Describe the solution you'd like**
Create a table of contents with links to the different sections. There may be a need to change some of the structure of the document as well.

**Comment by oyvindhermansen** [comment]
I agree that the docs are getting big. TOC is one solution, but we should also discuss the possibilities of making a docs-website.

**Comment by oyvindhermansen** [comment]
If we make a docs website, we can also have an examples page in there with live examples/code (maybe embed from codesandbox). This is just suggestions, but I would actually like having a website to gather all the docs.

**Comment by okaune** [comment]
Maybe a TOC could be seen as a temporary solution then? Until a docs website is in place?

**Comment by oyvindhermansen** [comment]
We can do that.
